steps:
  # 1. Install frontend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install frontend dependencies'
    args: ['install']
    dir: 'frontend'

  # 2. Install Node.js API dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install API dependencies'
    args: ['install']
    dir: 'backend/api'

  # 3. Install Python translator dependencies
  - name: 'python:3.11' # Match runtime from firebase.json
    id: 'Install translator dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    dir: 'backend/translator'

  # 4. Build the React frontend for production
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build frontend'
    args: ['run', 'build']
    dir: 'frontend'
    waitFor: ['Install frontend dependencies']
    env:
      - 'REACT_APP_API_KEY=$_API_KEY'
      - 'REACT_APP_AUTH_DOMAIN=$_AUTH_DOMAIN'
      - 'REACT_APP_PROJECT_ID=$PROJECT_ID'
      - 'REACT_APP_STORAGE_BUCKET=$_STORAGE_BUCKET'
      - 'REACT_APP_MESSAGING_SENDER_ID=$_MESSAGING_SENDER_ID'
      - 'REACT_APP_APP_ID=$_APP_ID'

  # 5. Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build frontend container'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/build-interprebot:$COMMIT_SHA', '.']
    dir: 'frontend'
    waitFor: ['Build frontend']

  # 6. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push frontend container'
    args: ['push', 'gcr.io/$PROJECT_ID/build-interprebot:$COMMIT_SHA']
    waitFor: ['Build frontend container']

  # 7. Deploy frontend container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'build-interprebot' # The service name
      - '--image=gcr.io/$PROJECT_ID/build-interprebot:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['Push frontend container']

  # 8. Deploy to Firebase Functions
  # This step deploys only the function codebases defined in firebase.json.
  - name: 'gcr.io/firebase/firebase'
    id: 'Deploy to Firebase'
    args:
      - 'deploy'
      - '--project'
      - '$PROJECT_ID' # Injects the project ID from the build environment
      - '--only'
      - 'functions' # Only deploying functions now
      - '--non-interactive'
    waitFor:
      - 'Install API dependencies'
      - 'Install translator dependencies'

# Timeout for the entire build process
timeout: '1200s'
